### ISSUE TITLE
Move to Python3

### ISSUE THREAD

**Issue by prkunz** [nasa/IDF#64]
Apple removed Python2.7 from new Mac OS update. This breaks anything that doesn't explicitly use Python3

A fix seems to be to change the first line of [IDF/bin/idf-config](https://github.com/nasa/IDF/blob/master/bin/idf-config#1) to
`#!/usr/bin/env python3`

**Comment by dbankieris** [comment]
I believe all of the Python code in IDF will run under both Python 2 and 3, so I'm reluctant to require a specific version. However, [PEP 394](https://peps.python.org/pep-0394/) reveals that there is no standard shebang to use whatever version of Python is installed. I've found a few options:

1. Rewrite `idf-config` to be a bash script instead of Python
2. Write a wrapper script to determine the available versions of Python and execute `idf-config` with one of them
3. Use this [here document hack](https://unix.stackexchange.com/a/66219) to have `idf-config` execute itself with some available version of Python
4. Require Python 3

Option 1 is the probably the best, but option 4 is certainly the easiest!

**Comment by prkunz** [comment]
Testing with option 4 has worked. I believe that the 12.3 update to OS X just completely removed Python 2 including the definition of the `python` command so that only the `python3` command is defined.

Option 1 probably is the best. I expect that we'll see distros using a mixture of definitions for python/python3. 

RHEL 8 and OS X will work with `python3` for the foreseeable future. But it's only a matter of time before a distro stops defining `python3` and it will break option 4.

**Comment by dbankieris** [comment]
I'll quietly look the other way if you choose the easy way out for now ;-)

**Comment by prkunz** [comment]
Oh, I didn't know you could start the script as a normal shell and then move into python like that. Makes sense.

**Comment by dbankieris** [comment]
@prkunz You should be able to delete `monterey` and use `master` now.
